sudo: false

language: java

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

cache:
  directories:
    - '$HOME/.m2/repository'

script:
  - mvn -B cobertura:cobertura coveralls:cobertura
  - rm -rf $HOME/.m2/repository/com/samskivert/jmustache
